name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.1
        with:
          go-version: 1.17.x

      - name: Build
        run: make manager

      - name: Ensure no files were modified as a result of the build
        run: git update-index --refresh && git diff-index --quiet HEAD -- || git diff --exit-code
